#!/bin/bash

red="\033[1;31m"
white="\033[1;37m"

if [ $# != 1 ]; then
	echo -e "$red[ERR-103] builder_ant needs only 1 parameter : the name of the package$white"
	exit 103
fi

ant run
if [ ! -e "build/jar/$1.jar" ]; then
	echo -e "$red[ERR-700] There is not $1.jar in build/jar/$white"
	exit 700
fi
for $file in *; do
	if [ "$file" != "DEBIAN" -a "$file" != "opt" -a "$file" != "usr" ]; then
		mv $file opt/packebian/$1
	fi
done
touch $1
chmod u+x $1
echo '#!/bin/bash' > $1
echo "" >> $1
echo "java -jar ../../../opt/packebian/$1/build/jar/$1.jar" >> $1
mv $1 usr/local/bin
