#!/bin/bash

red="\033[1;31m"
white="\033[1;37m"

if [ $# != 1 ]; then
	echo -e "$red[ERR-102] builder_maven needs only 1 parameter : the name of the package$white"
	exit 102
fi

mvn install
if [ ! -e "target/$1.jar" ]; then
	echo -e "$red[ERR-600] There is not $1.jar in target/$white"
	exit 600
fi
for $file in *; do
			if [ "$file" != "DEBIAN" -a "$file" != "opt" -a "$file" != "usr" ]; then
					mv $file opt/packebian/$1
			fi
	done
touch $1
chmod u+x $1
echo '#!/bin/bash' > $1
echo "" >> $1
echo "java -jar ./opt/packebian/$1/target/$1.jar" >> $1
mv $1 usr/local/bin

exit 0
