#!/bin/bash

red="\033[1;31m"
white="\033[1;37m"

if [ $# != 1 ]; then
	echo -e "$red[ERR-101] builder_makefile needs only 1 parameter : the name of the package$white"
	exit 101
fi

for file in *; do
	if [ "$file" != "DEBIAN" -a "$file" != "opt" -a "$file" != "usr" ]; then
		mv $file opt/packebian/$1
	fi
done

cd opt/packebian/$1
echo "[INFO] Compilation of sources"
make
for file in *; do
	if [ -x "$file" ]; then
		mv $file ../../../usr/local/bin
	fi
done
cd ../../..

exit 0
