#!/bin/bash

# @author: Thibaut Nouguier
# @pathway: RICM5
# @version: 2.0

red="\033[1;31m"
white="\033[1;37m"

# Check if the project contains a makefile
if [ ! -e makefile ]; then
	# There is not a makefile, then let's move on to another case.
	exit 50
fi

echo "[INFO] There is a makefile"
# Check parameters
if [ $# -lt 1 ]; then
	echo -e "$red[ERR-201] builder_makefile needs 1 parameter : the name of the package$white"
	exit 201
fi

# Clean the directory
for file in *; do
	if [ "$file" != "DEBIAN" -a "$file" != "opt" -a "$file" != "usr" ]; then
		mv $file opt/packebian/$1
	fi
done

# Compile sources and move binaries into usr/local/bin
cd opt/packebian/$1
echo "[INFO] Compilation of sources"
make
for file in *; do
	if [ -x "$file" ]; then
		mv $file ../../../usr/local/bin
	fi
done
cd ../../..

exit 0
