#!/bin/bash

# @author: Thibaut Nouguier
# @pathway: RICM5
# @version: 2.0

red="\033[1;31m"
white="\033[1;37m"

# Check if the project is a MAVEN Project
if [ ! -e pom.xml ]; then
	# There is not a pom.xml, then let's move on to another case.
	exit 50
fi

echo "[INFO] Maven project"
# Check parameters
if [ $# -lt 2 ]; then
	echo -e "$red[ERR-202] builder_maven needs 2 parameters : the name of the package and the version$white"
	exit 202
fi

# Build the project to create the jar file
mvn install
if [ ! -e "target/$1-$2.jar" ]; then
	echo -e "$red[ERR-303] There is not $1-$2.jar in target/$white"
	exit 303
fi

# Clean the project
for file in *; do
	if [ "$file" != "DEBIAN" -a "$file" != "opt" -a "$file" != "usr" ]; then
		mv $file opt/packebian/$1
	fi
done

# Create a command to execute the jar and move it into usr/local/bin
touch $1
chmod ugo+x $1
echo '#!/bin/bash' > $1
echo "" >> $1
echo "java -jar /opt/packebian/$1/target/$1-$2.jar" >> $1
mv $1 usr/local/bin

exit 0
